// <auto-generated />
namespace TM_IssueTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixedCascadeissues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedCascadeissues));
        
        string IMigrationMetadata.Id
        {
            get { return "201608251256508_Fixed Cascade issues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
